trigger:
- main

pool:
  vmImage: "ubuntu-latest"

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '8'  # Adjust the Java version as per your project requirements
    addToPath: true

- script: 'mvn clean package'
  displayName: 'Build with Maven'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/target'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'
    pathToPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'